# configuration options available at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# This configuration implements every package-ecosystem entry with the following logic:
# - only manage direct dependencies, as opposed to transient dependencies which are harder to maintain at scale

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"