version: "1"

templates:
  - name: slack
    source: git.target.com/TargetOSS/vela-templates/slack/slack.yml@master
    type: github
  - name: build-release
    source: git.target.com/TargetOSS/vela-templates/libraries/build_release_template.yml@master
    type: github

secrets:
  - name: artifactory_username
    key: TargetOSS/artifactory_username
    engine: native
    type: org
  - name: artifactory_password
    key: TargetOSS/artifactory_password
    engine: native
    type: org
  - name: slack_webhook
    key: TargetOSS/slack_webhook
    engine: native
    type: org
  - name: pull_request_api_key
    key: TargetOSS/pull_request_api_key
    engine: native
    type: org

steps:
  - name: build-release
    template:
      name: build-release
      vars:
        build_command: ./gradlew clean build jacocoTestReport --stacktrace
        build_release_image: library/openjdk:11-jdk
  - name: test-step
    image: library/openjdk:11-jdk
    pull: not_present
    ruleset:
      event: pull_request
    commands:
      - echo "begin test step"
      - echo "${VELA_REPO_NAME%-v*}"
      - echo "${VELA_BUILD_TAG##v}"
      - lscpu
      - top -b -n1
      - java -version
      - pwd
      - find . -name jacocoTestReport.xml
      - echo "end test step"
      - ls -l ./build/reports/jacoco/test/jacocoTestReport.xml
      - cat ./build/reports/jacoco/test/jacocoTestReport.xml
  - name: check-pr-code-coverage
    image: docker.target.com/app/pull-request-code-coverage
    pull: true
    secrets:
      - source: pull_request_api_key
        target: plugin_gh_api_key
    ruleset:
      event:
        - pull_request
    detach: false
    parameters:
      coverage_file: build/reports/jacoco/test/jacocoTestReport.xml
      coverage_type: jacoco
      gh_api_base_url: https://git.target.com
      source_dirs:
        - src/main/kotlin
