version: "1"

templates:
  - name: slack
    source: git.target.com/TargetOSS/vela-templates/slack/slack.yml@master
    type: github
  - name: build-release
    source: git.target.com/TargetOSS/vela-templates/libraries/build_release_template.yml@master
    type: github

secrets:
  - name: artifactory_username
    key: TargetOSS/artifactory_username
    engine: native
    type: org
  - name: artifactory_password
    key: TargetOSS/artifactory_password
    engine: native
    type: org
  - name: slack_webhook
    key: TargetOSS/slack_webhook
    engine: native
    type: org

steps:
  - name: build-release
    template:
      name: build-release
      vars:
        build_command: ./gradlew clean build --stacktrace
        publish_command: ./gradlew -Prelease.useLastTag=true -Prelease.disableGitChecks=true clean build artifactoryPublish -PartifactoryPublishRepositoryUsername=$ARTIFACTORY_USERNAME -PartifactoryPublishRepositoryPassword=$ARTIFACTORY_PASSWORD --stacktrace
        build_release_image: library/openjdk:11-jdk
