[versions]
caffeine = "3.2.0"
guava = "33.4.8-jre"
jupiter = "5.12.1"
kotest = "5.9.1"
kotlin-core = "2.1.0"
kotlin-logging = "7.0.6"
logback = "1.5.18"
micrometer-core = "1.14.6"
mockk = "1.13.17"
objenesis = "3.4"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlinlogging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
guava-testlib = { module = "com.google.guava:guava-testlib", version.ref = "guava" }
objnesis = { module = "org.objenesis:objenesis", version.ref = "objenesis" }
micrometer-core = { module = "io.micrometer:micrometer-core", version.ref = "micrometer-core" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }
kotest-extensions = { module = "io.kotest:kotest-extensions", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property-jvm", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[bundles]
testing = ["guava-testlib", "jupiter-api", "jupiter-engine", "jupiter-params", "kotest-assertions-core", "kotest-junit5", "kotest-property", "kotest-assertions-json", "kotest-extensions", "logback-classic", "mockk"]